### ISSUE TITLE
How to visualize the pointcloud

### ISSUE THREAD

**Issue by sangych** [SICKAG/sick_ldmrs_laser#10]
I have run the driver successfully, and "rostopic list echo /cloud" return the cloud msg. However, when I try to observe the pointcloud by rviz, adding the /cloud by topic, caused something error, no cloud was shown @mintar what's the correct way to visualize the pointcloud? thanks

**Comment by mintar** [comment]
Was there any error message?

**Comment by sangych** [comment]
Thanks for your reply ! I found that the wrong frame causing my problem and it was solved now, I will close this issue now.
