### ISSUE TITLE
How to visualize the /objects ?

### ISSUE THREAD

**Issue by sangych** [SICKAG/sick_ldmrs_laser#11]
Hi @mintar I can see the /objects topic with rostopic echo command, but it seemed that rviz can't add  the /objects topic. How  could visualize the /objects ?

**Comment by mintar** [comment]
Hi @sangych , you need to start the `sick_ldmrs_object_marker` node. It subscribes to the `objects` topic and publishes the topic `object_markers` of type `visualization_msgs/MarkerArray`, which you can then visualize in RViz.
