### ISSUE TITLE
Callback is crashing my main node

### ISSUE THREAD

**Issue by luhbartels** [SICKAG/sick_ldmrs_laser#12]
I'm using two LDMRS sensors on my project, so I launched two nodes, each one with the right ip address. 
I launch them, ok, works.
If I launch rqt, I cannot read the objects data. It shows me something like "not possible to reach sick_ldmrs_msgs/ObjectArray.h", even so, if I call the topics on my main node, I receive all incoming data from both sensors.

And then, suddenly this main node dies "process has die [pid... something]" but not the lidar's nodes. 
If I launch rqt again now, I can read all incoming data from both sensors.

It seems that when rqt accesses the sick_ldmrs_msgs/ObjectArray.h it crashes my main node.

Did it hapen to someone?

**Comment by mintar** [comment]
We only have one LD-MRS, so I cannot test this. It would be helpful if you could write the exact error message, and which commands you were running.

**Comment by PAWAS123** [comment]
Hi @luhbartels,
                        I am also working with two sick LDMRS lidars but have no idea how to modify the launch file to be able to connect to two lidars simultaneously.can you help by sharing a sample copy of the launch file.
Thanks in advance

**Comment by mintar** [comment]
Already tracked in #17.
