### ISSUE TITLE
Driver for LD-MRS to ROS Melodic Morenia

### ISSUE THREAD

**Issue by apletta** [SICKAG/sick_ldmrs_laser#13]
Hello SICK!

I have an LD-MRS unit that I'm trying to connect to ROS Melodic Morenia. Per the sick_ldmrs_laser ROS wiki and github it seems there isn't a driver for this distribution yet. Can you help me build/find a driver? I'll include the links to the wiki and github below. Thanks!

http://wiki.ros.org/sick_ldmrs_laser
https://github.com/SICKAG/sick_ldmrs_laser

**Comment by mintar** [comment]
This driver works fine with melodic, simply follow the install instructions. I've added a `melodic` branch (which is just an alias for the `kinetic` branch at the moment, so it doesn't really matter which branch you use).

**Comment by apletta** [comment]
Ok sounds good, we'll give it a shot. Thanks!
