### ISSUE TITLE
LD-MRS400001S01 error registers issue

### ISSUE THREAD

**Issue by mrashidmaqbool** [SICKAG/sick_ldmrs_laser#18]
Hello,
I am using a SICK Lidar (LD-MRS400001S01) to get a point cloud. The issue is that I am getting an error with the error registers. 

Error are in the below picture:
![Screenshot from 2020-08-31 17-31-46](https://user-images.githubusercontent.com/44435543/92385884-02b04300-f113-11ea-85a3-f160f6783711.png)

If i change the scan the scan frequency, the error register 2 changes to 0x0400. 

In addition, the line ( rosrun rqt_robot_monitor rqt_robot_monitor) generates the following error
![error_last_line](https://user-images.githubusercontent.com/44435543/92386083-5d499f00-f113-11ea-9b35-8fd207a45189.png)

Any help to resolve the above mentioned issues.

**Comment by mrashidmaqbool** [comment]
@mintar 
Please review

**Comment by mintar** [comment]
I can't help you with the first problem; please contact SICK directly about that.

About your second problem: That's very strange. The python module "rospkg" is defined in the debian package `python-rospkg-modules`, and `ros-melodic-rqt-robot-monitor` depends on `python-rospkg-modules`, so I have no idea how this can happen. Maybe just try "sudo apt update && sudo apt upgrade && apt install --reinstall python-rospkg-modules && ros-melodic-rqt-robot-monitor". If that doesn't help, your system is seriously messed up; perhaps somebody messed manually with the files in `/opt/ros/melodic` (you should never do that).

**Comment by mrashidmaqbool** [comment]
Thankyou for your help. I have tried on other machine and second part is working fine.
