### ISSUE TITLE
ROS2 Drivers?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [SICKAG/sick_ldmrs_laser#19]
Will you release any ROS2 drivers?

**Comment by mintar** [comment]
I am not planning to port this driver to ROS2 at the moment. If anyone is interested, I would be glad to review pull requests however!

**Comment by Kaju-Bubanja** [comment]
There actually are ROS2 drivers, I just didn't find them at first: https://github.com/SICKAG/sick_scan2
