### ISSUE TITLE
'Intensity Value of the Point Cloud'

### ISSUE THREAD

**Issue by turtleMaster20** [SICKAG/sick_ldmrs_laser#21]
I am trying to apply color to the Point Cloud based on the intensity values.

However, it seems that the cloud has no field called `intensity`. Is there an alternative name that has been assigned to this property?

**Comment by mintar** [comment]
There's a field called `echowidth` that roughly corresponds to intensity.

**Comment by turtleMaster20** [comment]
Thanks
