### ISSUE TITLE
How can I add Ring value into /cloud?

### ISSUE THREAD

**Issue by fouad1995** [SICKAG/sick_ldmrs_laser#22]
The ring value is not published inside the cloud, and I need to add ring number of each point

**Comment by mintar** [comment]
The number of the ring is called `layer` and is already published in the cloud: https://github.com/SICKAG/sick_ldmrs_laser/blob/a8e4f108821bf29fc098f0a26814a418927768f9/sick_ldmrs_msgs/include/sick_ldmrs_msgs/sick_ldmrs_point_type.h#L13
