### ISSUE TITLE
driver node issues

### ISSUE THREAD

**Issue by RiccardoFerrarese** [SICKAG/sick_ldmrs_laser#24]
I would use this package in a conda-ros environment, but at the moment of running catkin_make_isolated I found this error: 

In file included from /home/ros/anaconda3/envs/ros_env/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /home/ros/anaconda3/envs/ros_env/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /home/ros/anaconda3/envs/ros_env/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /home/ros/anaconda3/envs/ros_env/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /home/ros/anaconda3/envs/ros_env/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /home/ros/anaconda3/envs/ros_env/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /home/ros/anaconda3/envs/ros_env/include/boost/shared_ptr.hpp:17,
                 from /home/ros/anaconda3/envs/ros_env/include/ros/forwards.h:37,
                 from /home/ros/anaconda3/envs/ros_env/include/ros/common.h:37,
                 from /home/ros/anaconda3/envs/ros_env/include/ros/ros.h:43,
                 from /home/ros/anaconda3/envs/ros_env/include/pcl_conversions/pcl_conversions.h:42,
                 from /home/ros/ros_vision/src/sick_ldmrs_laser/sick_ldmrs_driver/src/sick_ldmrs_node.cpp:39:
/home/ros/anaconda3/envs/ros_env/include/boost/bind.hpp:36:1: note: '#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.'
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
/home/ros/anaconda3/envs/ros_env/include/boost/function_output_iterator.hpp:14:1: note: '#pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.'
   14 | BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/home/ros/ros_vision/src/sick_ldmrs_laser/sick_ldmrs_driver/src/sick_ldmrs_node.cpp: In member function 'virtual void sick_ldmrs_driver::SickLDMRS::setData(datatypes::BasicData&)':
/home/ros/ros_vision/src/sick_ldmrs_laser/sick_ldmrs_driver/src/sick_ldmrs_node.cpp:140:61: error: conversion from 'boost::detail::sp_if_not_array<pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point> >::type' {aka 'boost::shared_ptr<pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point> >'} to non-scalar type 'pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point>::Ptr' {aka 'std::shared_ptr<pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point> >'} requested
  140 |       PointCloud::Ptr cloud = boost::make_shared<PointCloud>();
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

**Comment by RiccardoFerrarese** [comment]
I changed with the boost prefix, but the problem still remain on: 

error: conversion from 'boost::detail::sp_if_not_array<pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point> >::type' {aka 'boost::shared_ptr<pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point> >'} to non-scalar type 'pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point>::Ptr' {aka 'std::shared_ptr<pcl::PointCloud<sick_ldmrs_msgs::SICK_LDMRS_Point> >'} requested 140 | PointCloud::Ptr cloud = boost::make_shared<PointCloud>();

in setData function

**Comment by jspricke** [comment]
Should be fixed now as well.

**Comment by RiccardoFerrarese** [comment]
Yeah, with pcl::make_share its works. thanks!
