### ISSUE TITLE
Indigo Compilation Error

### ISSUE THREAD

**Issue by atasoglou** [SICKAG/sick_ldmrs_laser#4]
Hello,

got the following compilation error when compiling branch indigo:

````CMake Error at sick_ldmrs_laser/sick_ldmrs_driver/CMakeLists.txt:16 (find_package):
  By not providing "FindSickLDMRS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "SickLDMRS", but CMake did not find one.````

**Comment by mintar** [comment]
You probably didn't install `libsick_ldmrs`, which is required by this project. Please follow the installation instructions verbatim:

https://github.com/SICKAG/sick_ldmrs_laser#from-source

**Comment by atasoglou** [comment]
Omg, you are right, my bad!!! I saw the two lines of git cloning and I thought they were cloning the same repo so I skipped the first. They really look identical (except the branch part).

**Comment by mintar** [comment]
Glad I could help! :)
