### ISSUE TITLE
cant see lidar points. ERROR

### ISSUE THREAD

**Issue by prango** [SICKAG/sick_ldmrs_laser#6]
![screenshot from 2017-06-22 03 04 21](https://user-images.githubusercontent.com/2040716/27407926-f883da44-56f7-11e7-9a63-3b795bd88487.png)

I have been getting this error while connecting with my SICK LD-MRS800001S01.

**Comment by mintar** [comment]
Can you ping 192.168.0.1? Is your laser scanner configured to use that IP (you can check using the Sopas ET tool on Windows)? Make sure to set the `hostname` parameter to the correct IP of the scanner.

**Comment by prango** [comment]
Yes i am able to ping. and just checked with the sopas ET and changed the IP to 192.168.0.1. still its showing the same error.

**Comment by jspricke** [comment]
Can you try to connect manually?
```
nc 192.168.0.1 12002
```

**Comment by prango** [comment]
No response fro the lidar side. does that mean its still not configured for the ip ?

**Comment by prango** [comment]
![screenshot from 2017-06-28 21 41 55](https://user-images.githubusercontent.com/2040716/27647951-a8af8c72-5c4a-11e7-8f22-9bace8e9e1a8.png)

**Comment by jspricke** [comment]
What do you mean by no response? Does `nc` stay open or error?

**Comment by prango** [comment]
It stays open without any output.

**Comment by jspricke** [comment]
ok, so the socket is available, I have no idea why it doesn't work. Could I maybe get access to the system?

**Comment by prango** [comment]
Do you have a team viewer account ?

**Comment by jspricke** [comment]
no, ssh would be perfect ;). You can contact me by mail.

**Comment by prango** [comment]
Sent !

**Comment by mintar** [comment]
You must give your eth0 device an IP in the 192.168.0.* range. Your ifconfig screenshot shows that you haven't.

**Comment by prango** [comment]
![screenshot from 2017-06-28 23 13 00](https://user-images.githubusercontent.com/2040716/27651878-5d024406-5c57-11e7-868b-259c10e31fad.png)

even after setting the eth0 connection to ip address the it throws the same error. The device perfectly works fine when connected to teh windows and operated through the sick software. Checked with the sopas software as well the ip is 192.168.0.1

**Comment by mintar** [comment]
The PC can't have the same IP address as the scanner. Try 192.168.0.2 for the PC.

**Comment by prango** [comment]
Thanks ! its working now @mintar  @jspricke  really appreciate you guys helping me out.

**Comment by hgaren** [comment]
Hello @jspricke 
I have tried to change eth0 ip for my PC  to 192.168.0.2. Also I increased the time out value to the 20000ms . Even now it does not working.
![screenshot from 2018-01-15 18 45 44](https://user-images.githubusercontent.com/16897319/34950719-0411e862-fa25-11e7-9a66-79387a6066f7.png)

**Comment by jspricke** [comment]
@hgaren wrong issue ;). I will continue to comment in #7
