### ISSUE TITLE
Could not Find  Sick MRS1000

### ISSUE THREAD

**Issue by hgaren** [SICKAG/sick_ldmrs_laser#7]
How to adapt with MRS1000 for this library.  While running the roslaunch sick_ldmrs_tools sick_ldmrs_demo.launch , it says :
 Info: Manager::addAndRunDevice: Created Device of type 3 with Name LDMRS-1 under the ID 1. Now initializing the device.
ERROR: Tcp::open: Failed to open TCP connection to 192.168.0.1, aborting.
ERROR: LuxBase::initTcp(): ERROR: Failed to establish TCP connection, aborting.
ERROR: LDMRS::init: Failed to initialize LuxBase - Device init failed, aborting.
ERROR: Manager::addAndRunDevice: Failed to initialize the device, aborting.
[ERROR] [1516026681.915360498]: Failed to add device LDMRS-1, aborting!

**Comment by jspricke** [comment]
can you make sure your Ethernet connection to the scanner is fine, can you ping the scanner?

**Comment by hgaren** [comment]
I figure out the TCP connection error.
Yes, my ethernet connection with scanner is fine. Now I am getting 
 sendSOPASCommand: failed attempt to read from socket: 125: Operation canceled
 get_datagram: no data available for read after 1000 ms
this type of error.

**Comment by jspricke** [comment]
This sounds similar to https://github.com/SICKAG/sick_ldmrs_laser/issues/6 can you try the proposals in there?

**Comment by jspricke** [comment]
with your computer on 192.168.0.2 (and the scanner on 192.168.0.1?) can you still ping it?

**Comment by hgaren** [comment]
Yes I still ping it.
64 bytes from 192.168.0.1: icmp_seq=12 ttl=64 time=3.02 ms
64 bytes from 192.168.0.1: icmp_seq=13 ttl=64 time=1.55 ms
64 bytes from 192.168.0.1: icmp_seq=14 ttl=64 time=1.41 ms

**Comment by jspricke** [comment]
can you do a tcpdump when starting the node?
`
sudo tcpdump host 192.168.0.1
`

**Comment by hgaren** [comment]
I am receiving this line , when I starting the node. 
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

**Comment by jspricke** [comment]
there should be output for every package send, try to ping the scanner and see if tcpdump gives output.

**Comment by hgaren** [comment]
Unfortunately  I dont see any output
![screenshot from 2018-01-15 19 28 28](https://user-images.githubusercontent.com/16897319/34952352-74c0a710-fa2a-11e7-9b49-7f8173bdfa4b.png)

**Comment by mintar** [comment]
This driver (`sick_ldmrs_laser`) is **not** compatible with the SICK MRS 1000, only with the SICK LD-MRS models listed in the Readme (which are completely different from the MRS 1000). The MRS 1000 is actually very similar from a software point of view to the SICK TiM line of scanners. We are currently working on a pull request to add MRS 1000 support to the `sick_tim` driver: uos/sick_tim#55 . The PR should hopefully get merged this week. Please use that repo for your scanner.
