### ISSUE TITLE
Failed to initialize MRS6124R

### ISSUE THREAD

**Issue by mikepolik** [SICKAG/sick_ldmrs_laser#9]
Hello,
the node fails to initialize our MRS6124R scanner. We checked in SOPAS, the IP address of our scanner is 192.168.0.1 as required.
How can we solve this problem?
Thank you

**Comment by mintar** [comment]
This node is for the LD-MRS scanners that are listed in the README. The MRS6xxx scanner you have is a completely different piece of hardware.
